# Generated by Django 3.0.4 on 2020-04-03 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200322_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 13, 8, 32, 263849, tzinfo=utc)),
        ),
    ]
